server:
 port: 5555
spring:
 application:
  name: admin-client
 boot:
  admin:
   client:
    url: http://localhost:9999
   instance:
    prefer-ip: true
management:
 endpoints:
  web:
   exposure:
    include: '*'
 endpoint:
  health:
   show-details: always