server:
  port: 8000
spring:
  application:
    name: simple-provider
    #mysql
  datasource:
    druid:
      url: jdbc:mysql://192.168.2.240:3306/smartent?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 1
      min-idle: 1
      max-active: 20 
      max-wait: 60000
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      #redis redis配置
  redis:
    host: linx01
    database: 0
    port: 6379
    jedis:
      pool:
        max-active: 1000
        max-idle: 10
        min-idle: 2
        #cache
  cache:
    type: redis
#eureka
eureka:
  client:
    service-url:
      defaultZone: http://linux01:8888/eureka
    instance-info-replication-interval-seconds: 1
    registry-fetch-interval-seconds: 1

#mybatis plus 配置
mybatis-plus:
    #配置mapper.xml路径
   mapper-locations: classpath:/mapper/**/*Mapper.xml
   #配置实体类路径
   typeAliasesPackage: cn.chujiang.**.entity
   global-config:
      db-config:
         id-type: auto
   configuration:
      map-underscore-to-camel-case: true
      cache-enabled: true
      auto-mapping-unknown-column-behavior: none
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    cn: 
      chujiang: debug
#监控
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
  endpoint:
    health:
      show-details: always