#端口号
server:
  port: 7010
#注册到eureka服务中心的服务名
spring:
  application:
    name: simple-consumer
#eureka服务中心地址，多个使用逗号隔开
eureka:
  client:
    service-url:
      defaultZone: http://linux01:8888/eureka
    instance-info-replication-interval-seconds: 1
    registry-fetch-interval-seconds: 1
feign:
  hystrix:
    enabled: true
#监控配置 不用管
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
  endpoint:
    health:
      show-details: always